### ISSUE TITLE
Task list for `.set_data`

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#1303]
* [ ] .set_data/1
* [ ] kitchen sink test
* [ ] set_hook for on_set_data
* [ ] api set_data hook
* [ ] fluent set_data hook
* [ ] fluent post_set_data hook
* [ ] history entry
* [ ] has_hooks sees
* [ ] hook_everything
* [ ] post_hook_everything
* [ ] should fire on_enter?  on_transition_to?  (probably not)
* [ ] Things related to #488
* [ ] Things related to #452
