### ISSUE TITLE
Specific examples of gallery entries

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#461]
These are things that would make good members of a gallery

* [ ] XKCD Python #281 
* [ ] Recipes #204
* [ ] Advent/euler #253
* [ ] Holiday machines #252
* [ ] Cooking #249
* [ ] Deepak #68 especially with arrange #366 
* [ ] Maybe chess #66?  
* [ ] Maybe kitchen sink #65 
* [ ] Why-because analysis #49 
* [ ] Decision trees #40 
* [x] Comedy flowcharts #48 
* [ ] Sequential function chart #41
