### ISSUE TITLE
Let's have a machine gallery!

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#462]
How was there not a top-level issue for this yet?  There were feature issues 😆 

* [ ] Gallery needs categories and sorting #248 
* [ ] Github-based auto-gallery #212 
* [ ] .gallery TLD #155
* [ ] Tutorial on submission #135 
* [ ] Specific examples of gallery entries #461
