### ISSUE TITLE
FSL needs a linter

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#463]
Might just be a consequence of compiliation (like maybe just a collection of warnings from a CLI,) but we obviously need a linter, since there's a bunch of issues about it

* [ ] GH app bot for linting #209 
* [ ] Linter should warn about islands #137 
* [ ] Linter should warn about missing annotations #52 
* [ ] #112 
* [ ] arguably #8 
* [ ] #210
* [ ] #240

**Comment by StoneCypher** [comment]
Duplicate of #1428.

The linter is now filed as the fsl lint subcommand #1428 under the v10 Lint cluster #1562.

Dispositioned in the #1849 legacy-milestone sweep.
