### ISSUE TITLE
New language concepts and features

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#468]
* [ ] Embeddable machine fragments #235 aka #160 
* [ ] Spread without self #142 
* [ ] Stripes #57 
* [ ] Cycles #56
* [ ] Hooks #255 
* [ ] Guards #412 
* [ ] Kinds #100 
* [ ] Style cascade #114 
* [ ] HTML-like labels #110
* [ ] Regular labels #117

**Comment by StoneCypher** [comment]
Closing as not planned: Big-picture checkbox list superseded by the era-milestone taxonomy; every live child is individually filed.

Dispositioned in the #1849 legacy-milestone sweep.
