### ISSUE TITLE
Tutorial material

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#477]
* [ ] How to contribute #206 
* [ ] Effective styling #161 (aka 136 and 104)
* [ ] The FSL book #132 
* [ ] How to make a usable embedded machine #131 
* [ ] How to make a renderable embeddable graph #130 
* [ ] How to convert a UI into an FSM #129 
    * [ ] How to drive React #99
* [ ] Lightweight working-in-JS #106
* [ ] Lightweight how-to-get-started #105

**Comment by StoneCypher** [comment]
Closing as not planned: Meta tracking list whose children are individually dispositioned into the era program; the tracker/umbrella organization supersedes it.

Dispositioned in the #1849 legacy-milestone sweep.
