### ISSUE TITLE
Top level topics

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#490]
* [ ] New language concepts and features #468 
* [ ] Visual improvements #479 
* [ ] Package quality issues #480
* [ ] Tutorial material #477 
* [ ] Editor quality of life improvements #466  
* [ ] Highlighter stuff #481 
* [ ] Machine gallery #462

**Comment by StoneCypher** [comment]
Closing as not planned: 2020-era meta list superseded by the 2026 era program's umbrella/topic structure (#1401-#1411 etc.); listed children remain independently tracked.

Dispositioned in the #1849 legacy-milestone sweep.
