### ISSUE TITLE
Currently known needed example machines

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#849]
Go scrape all the physical locations to extend this list

1. [ ] identity
2. [ ] light switch
3. [ ] 3-brightness lamp
4. [ ] doorway
5. [ ] locking doorway
6. [ ] 3-state traffic light
7. [ ] 4-state traffic light (with off)
8. [ ] Traffic light with `after` timers
9. [ ] interleaved machine examples (thanks @machinshin)
    1. [ ] a heartbeat / littlejohn (good example of operator after)
    2. [ ] a human and a series of pets, with emotional sensors and interaction behaviors (except on the cat)
10. [ ] full intersection
11. [ ] 4 basic states of matter
12. [ ] Extensive states of matter
13. [ ] tcp/ip
14. [ ] BGP
15. [ ] eMMC Transfer Mode
16. [ ] HTTP 1.0
17. [ ] SIP
18. [ ] turnstile
19. [ ] counter (easy example of state)
20. [ ] [phase diagram of water](https://medium.com/@ashwinpalo/phase-diagram-of-water-definition-and-explanation-4ca37a553033) (easy example of sensors, properties, and auto transitions)
21. [ ] coin-op vending machine
22. [ ] button grid vending machine
23. [ ] tiny cpu (thanks bryon, see below, tutorial on building large thing)
24. [ ] us state traversal (thanks @msmorgan)
25. [ ] box that only closes when empty (thanks @msmorgan, sensor demo)
26. [ ] blackjack opponent ai (thanks burny and distinctly forest)
27. [ ] baseball (thanks forest, tutorial on managing state, good example of mealy vs moore)
28. [ ] pong (thanks ryan)
29. [ ] dishwasher (thanks brp and distinctly xivix)
30. [ ] submit a form (thanks dmarr)
31. [ ] combo lock
32. [ ] konami code detector (thanks brp)
33. [ ] chomsky-style string acceptor (tape example)
34. [ ] stochastic weather (randomness example)
35. [ ] autodialler (thanks bryon)
36. [ ] user login (thanks bryon)
37. [ ] point to point protocol
38. [ ] ATM
39. [ ] Roller Coaster Tycoon NPC
40. [ ] Fully functioning UI brain w/ login and routing
41. [ ] Car door locks
42. [ ] Alarm clock
43. [ ] Person's emotional state.  States are happy, very_happy, sad, very_sad, angry, very_angry, neutral, confused.  Use properties to show results.  Actions are things like compliment and insult.
44. [ ] Oven (example of using sensors, after)
45. [ ] Simple routed UI
46. [ ] UI with login
47. [ ] Motion detector lamp
48. [ ] Central heating/air for a house design
49. [ ] Background connection management (connected / dropped / reconnect / disconnect)
50. [ ] AI-style pole on nose balancer
51. [ ] AI that can't be beat at Nim
52. [ ] AI that can't be beat at Connect 4
53. [ ] ticket tracker
54. [ ] string acceptor
55. [ ] string duplicator
56. [ ] telephone call
57. [ ] print boarding pass
58. [ ] tamagatchi
59. [ ] roguelike troll
60. [ ] Deepak Chopra
61. [ ] Decision tree
62. [ ] Number guessing game
63. [ ] Graph renderer (using tape input, good example of js objects as state and unexpected abilities)
64. [ ] Histographer
65. [ ] Descriptive statistics machine
66. [ ] Trie builder
67. [ ] Elevator control
68. [ ] Comedy dog brain
69. [ ] Full implementation of Tic Tac Toe
70. [ ] Full implementation of chess
71. [ ] Thermostat with hysteresis
72. [ ] timed ajax background cacher
73. [ ] npc behavior (thanks kev)
74. [ ] animation manager (thanks kev)
75. [ ] series of interlocking machines for zelda - various monsters, items, etc (thanks dominick)
76. [ ] markhov chain (thanks dominick)
77. [ ] show how single FSM for ready-to-fire for tower defense makes it much easier to model TD game
78. [ ] shipping status on package
79. [ ] driving around a map, where each intersection is a state (thanks dominick)
80. [ ] parse a floating point number (only one period, must know when number is over, minus in only one place)
81. [ ] poker server
82. [ ] use as a cron with operator after and self-transition
83. [ ] #249
84. [ ] #204
85. [ ] Things from #35
86. [ ] Parameterizable Roller Coaster Tycoon guest (thanks kev)
87. [ ] Implementation of the game Guess the Number
88. [ ] Implementation of the game Reigns
79. [ ] Implementation of the dice game Craps
79. [ ] Implementation of the card game War
79. [ ] Implementation of the board game Go Moku
79. [ ] Implementation of the software game Minesweeper
80. [ ] password strength meter
81. [ ] ... god, you're going to write a lisp for this, aren't you
82. [ ] ... and it's going to run on the cpu, isn't it 😢 

Related:

1. [ ] Use this to populate #837
2. [ ] Use this to populate #795
3. [ ] Use this to support #398

# Tiny CPU instructions

1. [ ] Load/store
    1. [ ] ld addr r1out
    1. [ ] st r1 addrout
    1. [ ] call_ex r1 addrout
1. [ ] Numeric
    1. [ ] inc r1out
    1. [ ] dec r1out
    1. [ ] eq r1 r2 r3out 
    1. [ ] lt r1 r2 r3out 
    1. [ ] rt r1 r2 r3out 
    1. [ ] lte r1 r2 r3out 
    1. [ ] rte r1 r2 r3out 
    1. [ ] add r1 r2 r3out 
    1. [ ] sub r1 r2 r3out 
    1. [ ] mult r1 r2 r3out 
    1. [ ] div r1 r2 r3out 
    1. [ ] mod r1 r2 r3out 
    1. [ ] round r1 r2out 
    1. [ ] floor r1 r2out
    1. [ ] ceil r1 r2out
1. [ ] Logical
    1. [ ] not r1 r2out
    1. [ ] and r1 r2 r3out
    1. [ ] or r1 r2 r3out
    1. [ ] xor r1 r2 r3out
    1. [ ] nand r1 r2 r3out
1. [ ] Jump
    1. [ ] jump r1addr
    1. [ ] jeq r1 r2 r3addr
    1. [ ] jne r1 r2 r3addr
    1. [ ] jlt r1 r2 r3addr
    1. [ ] jgt r1 r2 r3addr
    1. [ ] jlte r1 r2 r3addr
    1. [ ] jgte r1 r2 r3addr
1. [ ] String
    1. [ ] charat r1 r2idx r3out
    1. [ ] strconcat r1 r2 r3out
    1. [ ] substr r1 r2start r3end r4out

**Comment by StoneCypher** [comment]
Closing as not planned: Most listed items shipped in the 2026 corpus (traffic lights incl. after-timers and intersections, states of matter, extensive state), the outstanding-examples accounting (#1075) is closed, and the interleaved-machine remainder belongs to v11 systems work.

Dispositioned in the #1849 legacy-milestone sweep.
